Bump TLS-Attacker from 5.3.0 to v6.3.4 (#159)
* update dependency TLS-Attacker from 5.3.0 to 6.1.4

* WIP 5.3.0 to 6.1.4: fix generics errors
(Reference TLS-Attacker Commit 49af57bb871219fa2427dc33621e4e2cae42d10c)

* WIP 5.3.0 to 6.1.4: LayerStack receiveData parameter requires generics
(Reference TLS-Attacker Commit 6b0c072fdeec33b41d44031c19b21e6f4dd1db61)

* WIP 5.3.0 to 6.1.4: Connection removed firstTimeout
(Reference TLS-Attacker Commit a4fab98ea9b5856d3fab218dc6d34bbc5cdb4560)

* WIP 5.3.0 to 6.1.4: Rename LayerConfiguration to StackConfiguration
(Reference TLS-Attacker Commit 30260caf1fa15ce2ed061191dc8c6c1a0e321dac)

* WIP 5.3.0 to 6.1.4: Update modifiable-variable dependency
(Reference TLS-Attacker Commit 2adb191ffb001abe609228c71f77af5da1d3da5a)

* WIP 5.3.0 to 6.1.4: Use official CertificateDelegate type

* WIP 5.3.0 to 6.1.4: replace CertificateKeyType with x509attacker
(Reference TLS-Attacker Commit 8a75161ea63160b4a1dac620c9407715f80785ea)

* WIP 5.3.0 to 6.1.4: replace setCertificateListConfig with setCertificateEntryList
(Reference TLS-Attacker Commit 8cbdfa82067eae9c9159c13fc42b278fc93fe55c, 1e40faa3f2cd411a8e5fc33bf89930a8f8c09227)

* WIP 5.3.0 to 6.1.4: fix getCertSignatureTypeString function
(Reference TLS-Attacker Commit 1e40faa3f2cd411a8e5fc33bf89930a8f8c09227)

* WIP 5.3.0 to 6.1.4: fix sul.config
(Reference TLS-Attacker Commit 8f3bba03adb36dd04f4dae8ed6a3e4b1749de22c, 8cbdfa82067eae9c9159c13fc42b278fc93fe55c)

* WIP 6.1.4 to 6.3.3: change version number
fix maven dependency:analyze
And can fix runtime error "Exception in thread "main" java.lang.NoClassDefFoundError: org/xbill/DNS/TextParseException" without adding extra dependency

* WIP 6.1.4 to 6.3.3: stop unwanted logs and added a logger for easier debug

* WIP 6.1.4 to 6.3.3: fix compile error

* WIP 6.1.4 to 6.3.3: fix runtime null exception

* WIP 6.1.4 to 6.3.3: add patch so RSA private and public keys can be correctly set.

* WIP 6.1.4 to 6.3.3: fix initializeTransportHandler
So when we test Client implementations, the socket client address and port will be set
(Reference TLS-Attacker Commit 6f663747dc4ad109e229020e1489e2ff66393319, since they removed similar logic inside ServerUdpTransportHandler.java)

* fix: add patch for TLS-Attacker so EMPTY_CERTIFICATE will be correctly generated.
And also stop the warning logs from protocol.preparator.CertificateMessagePreparator.

* fix: map SignatureAlgorithm items to CertificateKeyType
After this fix, we can learn output RSA_CERTIFICATE instead of RSA_PKCS1_CERTIFICATE

* fix: add disable reordering patch for TLS-Attacker just like TLS-Attacker-v5.3.0.patch

* fix: update scandium.config so TLS-Attacker v6.3.3 can read without runtime error

* fix: add enum mapping for ECDSA signature algorithm

* add TLS-Attacker patch so ECDSA certificate configuration can be correctly set, and prevent unexpected X509Context reset.

* fix tinydtls_client.config format, so no runtime error

* fix client fuzzing: make udp layer behave as before, which will consume the first arrived ClientHello.

* fix: RSAClientKeyExchangePreparator.java uses wrong RSA private key, therefore we will get wrong decrypted PreMaster Secret.

* fix: PionDTLS-2-0-9_Client_psk regression test

* upgrade TLS-Attacker dependency from 6.3.3 to 6.3.4
Removed patches for RSAClientKeyExchangePreparator.java, TlsContext.java and Context.java

* Delete experiments/patches/TLS-Attacker-v6.3.3.patch

* Remove redundant casts from TlsStepContext.java

* Remove redundant casts from DtlsOutputMapper.java

* update patch for CertificateMessagePreparator.java

* remove redundant @SuppressWarnings("rawtypes")

* Remove BouncyCastle

* Remove org,bouncycastle:bcprov-jdk15on

* Revert BouncyCastle removal [ci skip]

* Revert BouncyCastle removal

---------

Co-authored-by: Kostis Sagonas <kostis@it.uu.se>